---
/urbanloco/online_fgo:
  ros__parameters:
    use_sim_time: true
    GNSSFGO:
      IntegratorBase:
        StateSensorSyncTimeThreshold: 0.03
        IMUSensorSyncTimeThreshold: 0.005

      NovatelIntegrator:
        notIntegrating: false
        useHeaderTimestamp: false
        integratorPlugin: "GNSSLCIntegrator"
        useForInitialization: true
        GNSSMeasurementFrequency: 1
        PVTSource: "oem7"   # oem7, ublox, navfix span
        hasHeading: false
        hasPitch: false
        hasRoll: false
        integrateAttitude: false
        integrateVelocity: false
        onlyRTKFixed: false


        solutionSyncQueueSize: 10
        MsgSyncLowerBound: 50000000

        fixedVelVar: 1.
        posVarScale: 1.
        velVarScale: 1.
        headingVarScale: 1.
        robustParamPos: 0.5
        robustParamVel: 0.5
        robustParamAtt: 0.5
        headingOffsetDeg: 0.

        attitudeFrame: "ned"
        attitudeType: "yaw"
        velocityFrame: "ned"
        velocityType: "3d"
        noiseModelAttitude: "Cauchy"
        noiseModelVelocity: "Cauchy"
        noiseModelPosition: "Cauchy"

        NovatelBestposTopic: "/novatel_data/bestpos"
        NovatelBestvelTopic: "/novatel/oem7/bestvel"
        NovatelHeadingTopic: "/novatel/oem7/dualantennaheading"

        ubloxPVTTopic: "/ublox_gps_node/navpvt"
        navfixTopic: "/ublox/fix"


      LIOIntegrator:
        notIntegrating: false
        integratorPlugin: "LIOIntegrator"
        pointCloudTopic: "/velodyne_points"
        lidarFrame: "velodyne"
        baselinkFrame: "base_link"
        odometryFrame: "odom"
        mapFrame: "map"
        savePCD: false
        savePCDDirectory: ""

        integrateBetweenPose: true
        integrateGlobalPose: false
        odomPoseVar: [ 0.5, 0.5, 0.5, .25, .25, .25 ]
        noiseModelOdomPose: "Cauchy"
        robustParamOdomPose: 0.1

        N_SCAN: 32
        Horizon_SCAN: 1800
        downsampleRate: 1
        lidarMinRange: 3.
        lidarMaxRange: 1000.
        maxPosePriorLiDARMsgAging: 0.1
        edgeFeatureMinValidNum: 10
        surfFeatureMinValidNum: 100
        numberOfCores: 8
        mappingProcessInterval: 0.15
        varianceRoll: 0.09
        variancePitch: 0.09
        varianceYaw: 0.09
        varianceX: 0.01
        varianceY: 0.01
        varianceZ: 0.04

        surroundingKeyframeSearchRadius: 50.
        loopClosureEnableFlag: true
        loopClosureFrequency: 1.
        surroundingKeyframeSize: 50
        historyKeyframeSearchRadius: 15.
        historyKeyframeSearchTimeDiff: 30.
        historyKeyframeSearchNum: 30
        historyKeyframeFitnessScore: 0.3
        globalMapVisualizationSearchRadius: 1000.
        globalMapVisualizationPoseDensity: 10.
        globalMapVisualizationLeafSize: 1.
        imuRPYWeight: 0.01
        z_tollerance: 1000.
        rotation_tollerance: 1000.
        mappingCornerLeafSize: 0.2
        mappingSurfLeafSize: 0.4
        surroundingkeyframeAddingDistThreshold: 0.2
        surroundingkeyframeAddingAngleThreshold: 0.2
        surroundingKeyframeDensity: 2.0

        maxNumCachedMap: 1000000
        maxPointAge: 10.
        scan2MapOptIteration: 30
        minSizeCurrentKeyframeCloud: 300
        minSizePreviousKeyframeCloud: 1000
        icpMaxIterations: 100
        icpTransformEpsilon: 1e-6
        icpEuclideanFitnessEpsilon: 1e-6
        icpRANSACIterations: 0
        freqLoopDetectionInSec: 5
        freqVisualizationInSec: 5




















