---
/deutschland/online_fgo:
  ros__parameters:
    use_sim_time: true
    GNSSFGO:
      VehicleParameterPrefix: "GNSSFGO"
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "novatel_ant_main", "novatel_ant_aux", "ublox_ant_main", "vlp16" ]
        imu:
          preRotate: [ 0., 0., 0. ]

        reference:
          transFromBase: [ -0.11, -0.49, -0.2085 ]
          rotFrameBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        novatel_ant_main:
          transFromBase: [ -0.11, -0.49, -0.2085 ]
          rotFrameBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        novatel_ant_aux:
          transFromBase: [ -0.11, 0.49, -0.2085 ]
          rotFrameBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        ublox_ant_main:
          transFromBase: [ 0., 0., -0.04 ]
          rotFrameBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        vlp16:
          transFromBase: [ 0.301411, 0., 0.0596 ]
          rotFromBase: [ 1., 0., 0., 0., -1., 0., 0., 0., -1. ]