---
/kitti/online_fgo:
  ros__parameters:
    GNSSFGO:
      VehicleParameterPrefix: "KITTI"

    KITTI:
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "gps", "lidar", ]
        imu:
          preRotate: [ 0., 0., 0. ]

        reference:
          transFromBase: [ -0.11, -0.49, -0.2085 ]
          rotFrameBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        gps:
          transFromBase: [ -0.11, -0.49, -0.2085 ]
          rotFrameBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]

        lidar:
          transFromBase: [ 0., 0., -0.04 ]
          rotFrameBase: [ 1., 0., 0., 0., 1., 0., 0., 0., 1. ]
