---
/boreas/online_fgo:
  ros__parameters:
    use_sim_time: true
    GNSSFGO:
      verbose: false
      useIMUAsTimeReference: true
      bufferSize: 10
      optFrequency: 10 #in Hz
      stateFrequency: 10
      calcErrorOnOpt: true
      cleanIMUonInit: true    # set this flag to clean the imu data before the timestamp of the initializing state
      useHeaderTimestamp: true
      imuTopic: "/boreas/imu/data"
      calibGravity: false
      #pubPoseVel: true
      #pubFGOState: true
      #pubPVTError: true
      #pubTimer: true
      #msg_lower_bound: 5000000 # 5 ms

      Initialization:
        initSigmaX: [ 1., 1., 1., 1., 1., 1. ] #first 3 for Rot in degree, other for translation in m
        initSigmaV: [ .1, .1, .1 ]
        initSigmaW: [ 0.05, 0.05, 0.05 ]
        initSigmaB: [ 0.5, 0.5, 0.5, 0.05, 0.05, 0.05 ] #first for b_a, second for b_g in degree
        initSigmaC: [ 1000., 10. ] #cb in m, cd in m/s

      IMUPreintegrator:
        accelerometerSigma: 0.008077134407821842 #3.9939570888238808e-04 #8e-4 # 8e-4
        integrationSigma: 1e-4 # 1e-4
        gyroscopeSigma: 0.0006939335887264338 #1.5636343949698187e-05   #52e-4 # 52e-5
        biasAccSigma: 4e-3 # 4e-4
        biasOmegaSigma: 87e-4 # 87e-5
        biasAccOmegaInt: 0.00001 # 0.00001

      Graph:
        IMUMeasurementFrequency: 200  #
        addGPPriorFactor: true
        gpType: 'WNOJ'  # 'WNOA'
        addGPInterpolatedFactor: true
        addEstimatedVarianceAfterInit: false

        AutoDiffNormalFactor: true
        AutoDiffGPInterpolatedFactor: true
        AutoDiffGPMotionPriorFactor: false
        GPInterpolatedFactorCalcJacobian: true

        StateMeasSyncUpperBound: 0.02
        StateMeasSyncLowerBound: -0.02
        addMMFactor: false
        addConstDriftFactor: false

        noiseModelClockFactor: "huber"
        robustParamClockFactor: 10.
        constDriftStd: 0.5
        constBiasStd: .1
        motionModelStd: 1.
        angularRateStd: 0.05
        magnetometerStd: 0.01

        NoOptimizationWhileNoMeasurement: false
        NoOptimizationNearZeroVelocity: false
        VoteNearZeroVelocity: 0.7 # 20%
        NoOptimizationAfterStates: 100

      Integrators: [ "BoreasGNSSLCIntegrator", ]   # [ "LIOIntegrator"]

      Optimizer:
        #undefined, BatchFixedLag, IncrementalFixedLag
        smootherType: 'IncrementalFixedLag'
        smootherLag: 5.0 #marginalization threshhold
        #QcGPWNOJInterpolator: 1000.
        #QcGPWNOJMotionPrior: 10000.
        QcGPWNOJInterpolatorFull: [ 10000., 10000., 10000., 10000., 10000., 10000. ]
        QcGPWNOJMotionPriorFull: [ 10000., 10000., 10000., 10000., 10000., 10000. ]
        #QcGPWNOAInterpolator: 0.5
        #QcGPWNOAMotionPrior: 0.5
        QcGPWNOAInterpolatorFull: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]
        QcGPWNOAMotionPriorFull: [ 0.5, 0.5, 0.5, 0.5, 0.5, 0.5 ]
