---
/boreas/online_fgo:
  ros__parameters:
    GNSSFGO:
      VehicleParameterPrefix: "Boreas"

    Boreas:
      VehicleParameters:
        baseFrame: "imu"
        sensors: [ "imu", "reference", "gps", "lidar", ]
        imu:
          preRotate: [ 0., 1., 0., 1., 0., 0., 0., 0., -1. ]

        reference:
          transFromBase: [ 0., 0., 0. ]
          rotFrameBase: [ 0., 1., 0., 1., 0., 0., 0., 0., -1. ]

        gps:
          transFromBase: [ 0., 0., 0. ]
          rotFrameBase: [ 0., 1., 0., 1., 0., 0., 0., 0., -1. ]

        lidar:
          transFromBase: [ -0.0249, 0.013439780101180,  -0.316013753414154 ]
          rotFrameBase: [ 0.707106781186548,  0.707106781186548,  0.,
                          0.707106781186548, -0.707106781186548,  0.,
                          0.,  0., -1.0 ]
